defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: /home/circleci/cotypeui

noStrictHost: &noStrictHost
  name: Disable strict host checking
  # We are not actually using ssh for communication with github
  # and semantic release has hickups from time to time
  # (https://circleci.com/gh/cotype/core/189)
  # Ref: https://github.com/semantic-release/semantic-release/issues/1095
  command: >
    mkdir ~/.ssh/ &&
    echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create package-lock.json checksum
          command: >
            sha256sum package-lock.json > .package-lock-sum
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum ".package-lock-sum" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum ".package-lock-sum" }}
      - save_cache:
          paths:
            - ~/cotypeui
          key: v1-repo-{{ .Revision }}
  lint:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - run:
          name: Lint
          command: npm run lint
  build:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - run:
          name: Build
          command: npm run build
      - save_cache:
          paths:
            - lib
          key: v1-build-{{ .Revision }}
  release:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - restore_cache:
          keys:
            - v1-build-{{ .Revision }}
      - run:
          <<: *noStrictHost
      - run:
          name: Release
          command: npx semantic-release || true
  pre-release:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - restore_cache:
          keys:
            - v1-build-{{ .Revision }}
      - run:
          <<: *noStrictHost
      - run:
          name: Pre-Release
          command: npx semantish-prerelease --release-pr || true

workflows:
  version: 2
  test-and-publish:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - release:
          requires:
            - lint
            - build
          filters:
            branches:
              only: master
      - pre-release:
          requires:
            - lint
            - build
          filters:
            branches:
              ignore: master
